language: android

android:
  components:  	
    - build-tools-22.0.1
    - android-22
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

script:
  ./gradlew build
